function [BF, out] = my_construct_bf_blackbox(...
    n, op_K, op_K_adjoint, ...
    x, xi, ...
    n_leaf_bf, r_bf, tol_bf, type_bf)

d = size(x, 2);

switch type_bf
    case "bf"
        if d == 1
            [BF, out] = bf1d_implicit_batch(...
                op_K, op_K_adjoint, ...
                x, [0, 1], ...
                xi, [-n / 2, n / 2], ...
                r_bf, tol_bf, 0);
        elseif d == 2
            [BF, out] = bf2d_implicit_batch(...
                op_K, op_K_adjoint, ...
                x, repmat([0, 1], d, 1), ...
                xi, repmat([-n / 2, n / 2], d, 1), ...
                r_bf, tol_bf, 0);
        else
            error("FIO:BFBlackBoxConstruct:UnsupportedDimension", ...
                "BF.m implicit construction only supports 1D and 2D problems.");
        end
    case "mbf"
        if d ~= 2
            error("FIO:BFBlackBoxConstruct:UnsupportedDimension", ...
                "BF.m MBF black-box construction only supports 2D problems.");
        end
        [BF, out] = mbf_implicit_batch(...
            op_K, op_K_adjoint, ...
            x, repmat([0, 1], d, 1), ...
            xi, repmat([-n / 2, n / 2], d, 1), ...
            r_bf, tol_bf, 0);
    case "pbf"
        if d ~= 2
            error("FIO:BFBlackBoxConstruct:UnsupportedDimension", ...
                "BF.m PBF black-box construction only supports 2D problems.");
        end
        [BF, out] = pbf_implicit_batch(...
            n, op_K, op_K_adjoint, ...
            x, repmat([0, 1], d, 1), ...
            xi, repmat([-n / 2, n / 2], d, 1), ...
            r_bf, tol_bf, 0);
    case "mybf"
        if d == 1
            BF = Butterfly(n, n_leaf_bf, 0);
        elseif d == 2
            BF = Butterfly2D(n, n_leaf_bf, 0);
        else
            error("FIO:BFBlackBoxConstruct:UnsupportedDimension", ...
                "BHP black-box construction only supports 1D and 2D problems.");
        end
        out = BF.BlackBoxConstruct(...
            op_K, op_K_adjoint, r_bf, tol_bf, 0);
    otherwise
        error("FIO:BFBlackBoxConstruct:UnsupportedType", ...
            "Unsupported black-box BF type: %s.", type_bf);
end

end
